force-app/main/default/objects/Case/fields/Dispute_Status__c.field-meta.xml
<CustomField>
    <fullName>Dispute_Status__c</fullName>
    <label>Dispute Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dispute Initiated</fullName>
            </value>
            <value>
                <fullName>Dispute Approved</fullName>
            </value>
            <value>
                <fullName>Dispute Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Is_Open__c.field-meta.xml
<CustomField>
    <fullName>Is_Open__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Open</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Settelment__c.field-meta.xml
<CustomField>
    <fullName>Settelment__c</fullName>
    <label>Settlement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending for approval</fullName>
            </value>
            <value>
                <fullName>Settlement Approved</fullName>
            </value>
            <value>
                <fullName>Settlement Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseTriggerHandler.cls
/**
* @author       TechMatrix Team
* @description Case Trigger Handler for Handle Case Trigger.
*/
public with sharing class CaseTriggerHandler {
    /**
* @description Ensure Comment mendatory for Approval proccess.
* 
* @param newCase List of new case 
* @param oldCase List of old case
* @param newCaseMap Map of new case
* @param oldCaseMap Map of old case
*/
    public static void onBeforeUpdate( List<Case> newCase, List<Case> oldCase, Map<ID, Case> newCaseMap , Map<ID, Case> oldCaseMap )
    {
        // Case Dispute Approval Process
        ApprovalProcessComment.ensureCommentOnApprovalChange(
            newCase,
            oldCaseMap,
            'Dispute_Status__c',
            'Dispute Approved',
            'Dispute Rejected',
            newCaseMap
        );
        
        // Settlement Approval Process
        ApprovalProcessComment.ensureCommentOnApprovalChange(
            newCase,
            oldCaseMap,
            'Settelment__c',
            'Settlement Approved',
            'Settlement Rejected',
            newCaseMap
        );
        
        List<String> forFalseOpen = new List<String>();
        List<String> forUpdateOpen = new List<String>();
        for (Case newCaseInstance : newCase) {
            Case oldCaseInstance = oldCaseMap.get(newCaseInstance.Id);
            if (newCaseInstance.Status != oldCaseInstance.Status && oldCaseInstance.Status == 'Open' && newCaseInstance.Status != 'Open') {
                forFalseOpen.add(newCaseInstance.Id);
            }
            if (newCaseInstance.Status != oldCaseInstance.Status && oldCaseInstance.Status != 'Open' && newCaseInstance.Status == 'Open') {
                forUpdateOpen.add(newCaseInstance.Id);
            }
        }
        if((!forFalseOpen.isEmpty() || !forUpdateOpen.isEmpty()) && !System.isBatch()){
            updateIsOpen(JSON.serialize(forFalseOpen),JSON.serialize(forUpdateOpen));
        }
    }
    
    /**
* @description future method for approval process comment test
* 
* @param forFalseOpen string 
* @param forTrueOpen string
*/ 
    @future 
    public static void updateIsOpen(String forFalseOpen, String forTrueOpen) {
        List<String> forFalseOpenList = (List<String>)JSON.deserialize(forFalseOpen, List<String>.class);
        List<String> forTrueOpenList = (List<String>)JSON.deserialize(forTrueOpen, List<String>.class);
        List<Case> caseData = new List<Case>();
        for(Case caseInstance : [SELECT Id FROM Case WHERE Id IN :forFalseOpenList WITH SECURITY_ENFORCED]) {
            caseData.add(new Case(Id = caseInstance.Id, Is_Open__c = false));
        }
        for(Case caseInstance : [SELECT Id FROM Case WHERE Id IN :forTrueOpenList WITH SECURITY_ENFORCED]) {
            caseData.add(new Case(Id = caseInstance.Id, Is_Open__c = true));
        }
        
        if(!caseData.isEmpty()){
            update as System caseData;
        }
    }
}