force-app/main/default/objects/Refund_and_Waive_off_Request__c/Refund_and_Waive_off_Request__c.object-meta.xml
<CustomObject>
    <label>Refund and Waive off Request</label>
    <nameField>
        <displayFormat>RW-{000000}</displayFormat>
        <label>Refund and Walve off Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refund and Waive off Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Refund_and_Waive_off_Request__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending for approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RefundAndWaiveOffHandler.cls
/**
 * @author       TechMatrix Team
 * @description Refund And Waive Off Handler.
 */
public with Sharing class RefundAndWaiveOffHandler {
     /**
     * @description Ensure Comment mendatory for Approval proccess.
     * 
     * @param newRefundWaiveOff List of refund and waive off new 
     * @param oldRefundWaiveOff List of refund and waive off old
     * @param newMapRefundWaiveOff Map of refund and waive off new
     * @param oldMapRefundWaiveOff Map of refund and waive off old
     */
	public static void onBeforeUpdate( List<Refund_and_Waive_off_Request__c> newRefundWaiveOff, List<Refund_and_Waive_off_Request__c> oldRefundWaiveOff, Map<ID, Refund_and_Waive_off_Request__c> newMapRefundWaiveOff , Map<ID, Refund_and_Waive_off_Request__c> oldMapRefundWaiveOff )
    {
        ApprovalProcessComment.ensureCommentOnApprovalChange(
            newRefundWaiveOff,
            oldMapRefundWaiveOff,
            'Approval_Status__c',
            'Approved',
            'Rejected',
            newMapRefundWaiveOff
        );
    }
}